### ISSUE TITLE
Set Up Routes for Site Navigation

### ISSUE THREAD

**Issue by matthewcoupal** [PotsdamACM/acm-meteor-app#7]
Utilizing the Iron-router package, wire the routes to allow for single-page application navigation of the site.

**Comment by matthewcoupal** [comment]
# A Small Router Package

I found a small client-side router that might help reduce requests to the server.
[page.js](https://visionmedia.github.io/page.js/)

**Comment by JessePeplinski** [comment]
@matthewcoupal - Close this if it is completed.
